on:
push:
tags:
-'v*
name: Create Release
jobs:
build:
name: Craete Release
runs-on: ubuntu-latest
steps:
-name: Checkout code
uses: actions/checkout@v2
-name: Create Release
id: create_release
uses: actions/create-release@v1
env:
GITHUB_TOKEN: ${{ github.ref }}
with:
tag_name: ${{ github.ref }}
release_name: Release ${{ github.ref }}
body: |
Changes in this Release
- First Change
- Second Change
draft: false
prerelease: false
